FarcicalPopsicle/faunadex

- PRESS-RELEASE.md
- README.md
Press release should be pretty solid. The readme only partially filled out, but should be modified as we get more information about our app and tests are create and we install it.
> PRESS-RELEASE.md and README.md added

- .bowerrc
- .gitignore
- bower.json
> Add Bower files

- schema.sql
- schema.xml
> Update schema in both xml and sql file

- client/bundle.js
- client/index.html
- client/models/app.js
- package.json
- webpack.config.js
No associated issue, I just wanted to push some minimal code to keep everything up to date
> Create basic react/webpack/hotloader skeleton

- dummies/dummies.js
- package.json
- server/config/middleware.js
- server/config/userUtils.js
- server/models/user.js
> Models and utilities

- dummies/dummies.js
- schema.sql
- schema.xml
- server/config/db.js
- server/config/encounterUtils.js
- server/config/routes.js
- server/config/utils.js
- server/models/encounter.js
Closes #51 
Closes #50 
Closes #16
> Encounters

- client/index.html
- client/index.js
- package.json
- webpack.config.js
I made it so that the $ jquery variable was available in all contexts
Closes #76
We'll need to use jquery to do ajax requests
Used manual testing
> Add ip address to config files and add jquery globally

- package.json
- server/config/middleware.js
- server/server.js
- test/auth.js
Provide the beginning of testing for auth
Connected to #75 
Starts tests for auth and adds some required modules
Manually tested
> Tests for auth

- package.json
> Error in package.json

- client/components/Encounter.js
- client/components/EncounterList.js
- client/components/User.js
- client/index.js
- dummies/dummies.js
I changed the dummy data to be arrays, since that is what we're going to get from the db.  I changed it so that when you try to get data from an immutable Map type object you use the get method.  I fixed a typo in the dummy data when camelCase was inconsistent.
Closes #83
> Clean encouters front end data

- client/components/EncounterList.js
- dummies/dummies.js
> Add ids to all items in dummy data and add it as key in EncountersList

- package.json
I had to reinstall because of a screwup on my part, and I found a missing module
By blood and sweat
> Add missing module cookie-parser

- test/auth.js
I changed the test so that it has a username that doesn't clash with another test
No related issue
I tested manually
> ## Description

- .github/PULL_REQUEST_TEMPLATE.md
Checkout hub, it's a command line interface for github, I'm not creating this pull
request via the command line!
No issue 
I'm doing it right now!
> Fix pull request template for hub users

- client/reducers/reducer.js
- package.json
I wanted to see all tests passing as well as failing so I removed the 
--bail from the `npm test` command.
Closes #94
I manually tested these changes and also ran `npm test`
> Clean the reducers function and remove --bail from test

- client/components/App.js
- client/components/Encounter.js
- client/components/EncounterList.js
- client/components/SignIn.js
- client/components/SignUp.js
- client/components/User.js
Eventually we'll want this when we style the app, so that we can style
all elements by class
closes #93
I inspected the elements in chrome to make sure the class names were added
> Add className attribute to all top-level JSX elements in components

- client/components/App.js
- client/index.js
- package.json
I added the redux-thunk middleware, which seems to streamline adding async
actions to the workflow by allowing dispatch to accept functions as well
as action objects.
Connected to #86
I have tested this manually
> Add middleware needed and give sample ajax call

- client/components/App.js
- client/components/SignIn.js
- client/reducers/reducer.js
This was harder than it looked.
I also fixed a couple of other errors on the way.
connects to #86
Tested manually
> Add a context for the signin component so it can change url dynamically

- server/config/routes.js
- server/utils/userUtils.js
import User module to userUtils to support createUser
add logInUser module to userUtils
add call to logInUser in post route to /api/user/signin
connected #61 
it is untested
will consider closed when it's tested an working
> add user log in module to userUtils.js, referenced in routes.js.

- Gruntfile.js
- client/components/Picture.js
- package.json
- webpack.config.js
I created a single grunt task for starting the server.  Now when you run npm start, it starts the server and watches for changes.
Closes #104 
Manually tested
> Grunt with webpack integration

- client/index.js
Hooray, AJAX is working!
Closes #109
Manual testing
> Cause initial encouters to be pulled from AJAX call to /api/user/encouter

- client/components/App.js
- client/components/NewEncounter.js
- client/components/UserProfile.js
- client/index.js
- client/reducers/reducer.js
- dummies/dummies.js
- server/config/routes.js
Added New Encounter component
Added user profile component
commented out unbuilt api routes
connected to #21 
connected to #106 
rendered and clicked through in the browser
> add components: NewEncounter.js and UserProfile.js

- client/components/SignIn.js
- server/config/routes.js
- server/utils/userUtils.js
changed redirect paths in logInUser
changed response to the current user 
changed isLoggedIn to send true or false responses to client
closes #61 
Tested using postman and clicking through app
> complete server-side authentication

- Gruntfile.js
It wasn't rerunning webpack so all the new code wasn't being compiled
Closes #116 
I tested this manually
> Make webpack run before starting server for the first time in npm start

- server/config/routes.js
- server/utils/encounterUtils.js
- test/01-Basic/01.first.test.server.js
Modified api endpoints for encounters to communicate with database
Modified encounter helper functions to communicate with database
Closed #111 
Connected #113 
Manual tested using Postman and dummy data and wrote tests for POST requests
> Database connection

- test/03-Auth/basic.js
These are only testing for the back end and posting to them directly without
testing the front end code.  New tests should be written in the future that test
the font end code using something like phantomjs
Closes #75
Tested manually... metatesting?
> Finish writing basic tests for auth

- client/components/App.js
- client/components/AuthNav.js
- client/components/Nav.js
- client/components/NoAuthNav.js
- client/index.js
- server/utils/userUtils.js
created parent component for auth and no-auth nav bars
added nav bar to all pages
removed nav bar switching logic from App.js
closes #132 
closes #134 
click-throughs, current testing suite (no new tests)
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.
> Nav bar on all pages

- Gruntfile.js
- client/index.js
- client/models/auth.js
- server/config/routes.js
- server/utils/userUtils.js
- test/03-Auth/basic.js
I created another function in index.js to handle the auth, and another
file which has some helper functions.  The additional file is probably not
needed, and may go away in the future
closes #121
Manually and also ran the backend tests
> Add authorization for front-end routes

- client/components/App.js
- client/components/EncounterList.js
- client/components/UserProfile.js
- client/index.js
- server/config/routes.js
- server/models/encounter.js
- server/models/user.js
- server/utils/encounterUtils.js
- test/01-Basic/01.first.test.server.js
Modified splash page so that it shows the most recent encounters instead of a users encounters
Modified user profile to use an get request to retrieve a user's encounters and display them
Modified Bookshelf user and encounter models to signify the relationship between the two
Modified showAllUsersEncounters function to take an :id that is the username and return the user's encounters
Closes #136 
Closes #119 
Connects to #107 
Modified tests to reflect change in api endpoint /api/user/encounters/:id
> User encounters

- client/components/Encounter.js
- client/components/EncounterListEntry.js
- client/components/UserProfile.js
- server/config/db.js
- server/models/encounter.js
- server/models/user.js
- server/utils/encounterUtils.js
Modify encounter endpoint functions to add the username to the encounters and updated the front-end to handle the change in data structure
Modify showAllEncountersFromUser to handle users with zero encounters instead of yielding an error
Add a bookshelfjs plugin 'registry' to make the above possible. It resolves circular dependencies
Closes #107
Closes #150
Closes #145 
Manually tested it with Postman and the site
> Encounter comp

- createTestData.js
- schema.sql
It takes a while, but creates 5 users with some encounters each.
Their login and passwords are the same
Closes #133
Manually, my database has the test data
> Script to create some test data for you to work with

- client/components/NewEncounter.js
- client/components/SignIn.js
- server/utils/userUtils.js
add userid to store on signin
closes #160 
npm test, click-throughs
> fix userid missing from store, new encounters now post to db

- client/components/NewEncounter.js
- schema.sql
- server/utils/encounterUtils.js
added animal type field to new encounters
added scientific name field to new encounters
added both to encounterUtils
added both to schema
closes #169 
click throughs, standard tests
> add animal type and scientific name fields to front and back ends

- client/components/Nav.js
- client/index.html
This adds a title to the html file and also makes the logo
a clickable link to the homepage
closes #148 
closes #163 
Manual testing and ran npm test as well
> Make small edits to clean up a couple of easy issues

- client/components/EncounterListEntry.js
There was a chained .get in EncouterListEntry.  You cannot ever used chained .get
you must use .getIn
Closes #176
Manually and checked automatic tests
> Fix Travis' mystery error with the 'Cannot read property get of undefined'

- client/components/SignIn.js
- client/components/SignUp.js
- client/index.js
- client/lib/auth.js
- client/lib/style.css
- client/reducers/reducer.js
- server/config/routes.js
- server/utils/userUtils.js
- test_server/03-Auth/basic.js
It now displays nice error messages on failed login and signup attempts
Closes #175
Manually ran plus npm test
> Add error messages

- client/components/EncounterListEntry.js
- createTestData.js
> add photos to dummy data, reduce size of encounter list entries

- client/components/SignIn.js
- client/components/SignUp.js
added links to sign in and sign up from their counterparts
closes #191 
click-throughs, npm test
> add links to sign in and sign up from their conterparts

- client/components/SignUp.js
added a space 
added links to sign in and sign up from their counterparts
added a space
closes #191 
click-throughs, npm test
> add a space in the string 'Already have an account? Sign in!'

- client/components/App.js
- client/components/EncounterDetails.js
- client/components/EncounterListEntry.js
- client/lib/style.css
Things look prettier, weeeeee!
Closes #195
Manually
> Add some styling to encounter elements

- client/components/EncounterListEntry.js
- client/lib/style.css
The main change is that now overflow is hidden on the list of elements. So
even if the text goes beyond the boxes, it doesn't look so ugly
Connected to #195
Manually
> Small style changes

- createTestData.js
> change bear picture

- client/components/Comment.js
- client/components/CommentList.js
- client/reducers/reducer.js
create two components for creating and rendering encounter comments
connects to #17 
not tested
> create commentList.js and Comment.js components

- schema.sql
- server/config/routes.js
- server/models/encounter.js
- server/models/post.js
- server/utils/postUtils.js
This creates api endpoints, and a model/utils for posts
connected to #17
Postman
> Make backend for posts

- client/components/UserProfile.js
- createTestData.js
- schema.sql
- server/utils/userUtils.js
add user photo to user profile
add user description to user profile
add these data to the store via userUtils.createSession
add dummy user photos
change default user photo
click throughs
> add features to user profile

- client/arkive-api-embed.js
- client/components/EncounterDetails.js
- client/components/EncounterListEntry.js
- server/utils/encounterUtils.js
Added the ARKive api from the EncounterListEntry page to the EncounterDetails page
Closes #209 
Manually
> Arkive details

- client/components/SignUp.js
- client/lib/auth.js
- server/utils/userUtils.js
add input fields to signup page and send values to database to be rendered on user profile page
click-throughs
> Add fields to signup

- client/components/Comment.js
- client/components/CommentList.js
- client/components/EncounterDetails.js
- client/components/EncounterListEntry.js
- client/index.js
- client/reducers/reducer.js
It posts comments, and gets them
Closes #17
Manually
> Create a commenting system

- createTestData.js
> fix squirrel image

- client/components/CommentList.js
- client/lib/style.css
> More styling on comments

- client/lib/style.css
> Width for user avatar

- README.md
> Create installation instructions

- README.md
> Remove doc stuff

- README.md
I'm adding a space to demonstrate waffle.io
Closes #220
> Add space to bottom of file

- server/server.js
Change port number to be variable
Manually
> Change port number to be variable
